### ISSUE TITLE
Possible error in source code file refrence

### ISSUE THREAD

**Issue by brettha** [editorscut/ec010functionalkickstart#1]
Functional Programming Kickstart: Release 0.1
Chapter: 1
Section: 7

Description:
Book versions 0.1

Paragraph Title: Dealing with errors
Example code: public func selectCard(at index: Int) -> (Card, Deck)

- It says to add the following to the function:
guard index < count else {...}

But the file the book references to add the code to is "01/Magic.playground/Sources/Card.swift"
I think the file should be 01/Magic.playground/Sources/Deck.swift
If I'm not mistaken

**Comment by editorscut** [comment]
Thank you! You are, of course, correct. Sorry for the mistake. I've made the correction in the version that goes out this Friday.
