### ISSUE TITLE
Question concerning intermediate results

### ISSUE THREAD

**Issue by thuroe** [editorscut/ec010functionalkickstart#10]
Functional Programming Kickstart: Release 0.4
Chapter: _4_
Section: _4_
Paragraph Safely force-unwrapping
Description: The final result on the changing works as you explain, but the intermediate results perplexes me. I would love to understand.
Attached a screen copy to the result in the playground.
![result unwrapping](https://user-images.githubusercontent.com/63961105/80991861-f7819980-8e38-11ea-8c14-d624bf550d6c.png)

MacOS: 10.15.5, beta3
Xcode : 11.4.1

**Comment by editorscut** [comment]
Remember twos = [2,4,6,8,10] there are five values.

If you right click on the box containing "false" you can toggle from most recent value to value history. You'll see five values indicating for 2,4,6,8,10 that the closure is false, true, false, true, false.

It is the two true values that are passed along by filter - so 4 and 8 survive to the map step

Again if you right click on the box containing eight and switch to value history you'll see both four and eight.

Image attached.

I hope that helped - I don't think it's needed in the book unless you feel strongly.

<img width="699" alt="Screen Shot 2020-05-04 at 2 43 56 PM" src="https://user-images.githubusercontent.com/1416181/81001682-1ae71d00-8e16-11ea-947c-e092fd855e41.png">

**Comment by thuroe** [comment]
Thank you very much.
I see that my question was due to the lack of knowledge of the way a playground works.
No need to include it in the book
