### ISSUE TITLE
fourOfHearts transformed into queenOfDiamonds

### ISSUE THREAD

**Issue by thuroe** [editorscut/ec010functionalkickstart#12]
Functional Programming Kickstart: Release 0.5
Chapter: _1_
Section: _Performing a simple trick_

Description:
Below the "4♥︎" it says:
_" Indeed we see that we pass the threeOfClubs to the function and the queenOfDiamonds is returned. "_
Should it not be:
_" Indeed we see that we pass the threeOfClubs to the function and the four of hearts is returned. "_
Or is there a subtlety that I did not capture?

**Comment by dimsumthinking** [comment]
Thank you this is fixed in the next release
