### ISSUE TITLE
Code to add is wrong color (it's in blue, not red)

### ISSUE THREAD

**Issue by brettha** [editorscut/ec010functionalkickstart#13]
Functional Programming Kickstart: Release 0.5
Chapter: 4
Section: 7

Description:
(minor) 
It says: Add identity() to BagOfTricks.swift. And then follows with the code to add.  But the code to add is in blue, I think it should be in red to indicate it needs to be added.

**Comment by dimsumthinking** [comment]
Thank you. I've fixed this for the next release
