### ISSUE TITLE
Return true instead of false?

### ISSUE THREAD

**Issue by brettha** [editorscut/ec010functionalkickstart#14]
Functional Programming Kickstart: Release 0.5
Chapter: 4
Section: 8

Description:
let boolFrom
    = exclaim
        .map{string in string.count}
        .map{int in int.isMultiple(of: 2) ? false : true}

Shouldn't int.isMultiple(of: 2) return true?  

BTW, this chapter really helped me out. When you said “For many developers, this is the only map() they know so the have it in their heads that map() is just syntactic sugar for a for loop” 
- ^ That was me!

Will we get a chapter similar to this for flatMap?  I took your combine workshop at TrySwift! and still am trying to wrap my head around what flatMap is doing.

**Comment by brettha** [comment]
My mistake, I was thinking it was saying "Hello!" is multiple of 2 but since we passed in "Hello", it makes sense we  return false.

**Comment by dimsumthinking** [comment]
Did you mark it closed for a reason or should I still look?

I’m working on the flatMap chapter and it’s taking longer than I want because I’m struggling to get the order right. THere’s so much I want to say!

Daniel
