### ISSUE TITLE
Knowing now

### ISSUE THREAD

**Issue by thuroe** [editorscut/ec010functionalkickstart#15]
Chapter: 5
Section: 7
Paragraph: Implementing of map
The strength of map() is that it allows us to work with functions that just **now** how to work with the contents of our context: what's in MagicHat, DustyTrunk, Array, or Optional. 

**now** should probably be **know**

**Comment by thuroe** [comment]
I do not know what happened this is in:
Functional Programming Kickstart: Release 0.5
Chapter: _5_
Section: _7 The Map Pattern_

**Comment by dimsumthinking** [comment]
Thank you - this is fixed for the next release.
