### ISSUE TITLE
Another one for the road

### ISSUE THREAD

**Issue by thuroe** [editorscut/ec010functionalkickstart#16]
Functional Programming Kickstart: Release 0.5
Chapter: _5_
Section: _7 The Map Pattern_

Description:
For many developers, this is the only map() they know so **the** have it in their heads that map() is just syntactic sugar for a for loop »

**the** should probably be **they**

**Comment by dimsumthinking** [comment]
Thank you - this is fixed for the next release (minutes from now!)
