### ISSUE TITLE
Ouuups, Map4 returns

### ISSUE THREAD

**Issue by thuroe** [editorscut/ec010functionalkickstart#17]
Functional Programming Kickstart: Release 0.6
Chapter: _6_
Section: _Front page_

Description: The header of the chapter says "MAP" and "Chapter 4", probably an error ported from the error in chapter 5 😀

**Comment by editorscut** [comment]
It sure was - thank you fixed in today's release

**Comment by thuroe** [comment]
Daniel,
I think that I have downloaded the latest version from Gumroad, and I have the impression that this error has sneaked back in

Lars
