### ISSUE TITLE
Are the [] not missing?

### ISSUE THREAD

**Issue by thuroe** [editorscut/ec010functionalkickstart#18]
Functional Programming Kickstart: Release 0.6
Chapter: _6_
Section: _Introduction_

Description:
Should the (String) in Bold in the below paragraph not rather be ([String]) ? 
Instead it could be the other half of the phrase that needs to be corrected, but it seems less plausible to me

_say we try to lift the function  f: **(String)** -> [Int] into the world of Arrays. The starting point of map(f) will be at an Array of Strings but the end point will be at an Array of Arrays of Ints._

**Comment by editorscut** [comment]
It's correct - I've added a sentence to try to make it more clear.
