### ISSUE TITLE
CardTrick -> TrickDeck

### ISSUE THREAD

**Issue by thuroe** [editorscut/ec010functionalkickstart#2]
Functional Programming Kickstart: Release 0.2
Chapter: _2_
Section: _2_
Paragraph: Naming a functions type

Description:
Text indicates to start with CardTrick, whereas the example uses TrickDeck

_« Start with a struct named CardTrick that holds a single property named trick which is a function (Deck) -> Deck.
02/FunctionsArentSpecial.playground/02TrickDeck
struct TrickDeck {
    let trick: (Deck) -> Deck
} "_

**Comment by editorscut** [comment]
Thank you. I renamed CardTrick to TrickDeck while writing and missed this. I really appreciate your help. This is fixed in Friday's release.
