### ISSUE TITLE
Function missing param

### ISSUE THREAD

**Issue by brettha** [editorscut/ec010functionalkickstart#22]
Functional Programming Kickstart: Release 0.6
Chapter: 6
Section: 2

Description:
The last example at the end of this section the code is:
newDeck
    .flatMap(shuffleDeck)
    .flatMap(cutDeck(to: 23))
    .flatMap(shuffleDeck)
    .flatMap(cutDeck(to: 17))

but the first function causes a compile error because the **to** param is not passed in.

**Comment by editorscut** [comment]
Thanks fixed
