### ISSUE TITLE
Minor (Misspelled data type name ShinyTrunk<Poijt>

### ISSUE THREAD

**Issue by brettha** [editorscut/ec010functionalkickstart#23]
Functional Programming Kickstart: Release 0.6
Chapter: 6
Section: 3

Description:
Title pretty much sums it up.  Under the subsection "Moving while aware of the Trunk" it says

“Otherwise we return a ShinyTrunk<Poijt> containing the movedPoint.”

**Comment by editorscut** [comment]
Thank you- this is fixed for today's release
