### ISSUE TITLE
function name mispelled (moveDownInTrunk)

### ISSUE THREAD

**Issue by brettha** [editorscut/ec010functionalkickstart#24]
Functional Programming Kickstart: Release 0.6
Chapter: 6
Section: 4 (“Using flatMap() for Result”)

Description:
"Look back at what we did in the previous two sections and implement movingRightInTrunk() and **moveDownInTrunk()** with types..."

I believe it the function name should be movingDownInTrunk()

**Comment by editorscut** [comment]
Thank you - fixed for today's release
