### ISSUE TITLE
Reference to variable that doesn't exist (yet)

### ISSUE THREAD

**Issue by bcmurray66** [editorscut/ec010functionalkickstart#29]
Functional Programming Kickstart: Release 0.7
Chapter: 1
Section: 6

Description: In "The idea of conditional conformance" there are references to the variable `coveredCard`, but the variable has not been declared yet (we call the `covered(_ covered:)` method, but don't assign the result). The result is that `coveredCard == coveredCard` won't compile, but not because `Equatable` hasn't been implemented on `BurnedCard`

**Comment by dimsumthinking** [comment]
Thank you - sorry I missed this - it's fixed for Friday's release.
