### ISSUE TITLE
Text incorrectly formatted as sample code

### ISSUE THREAD

**Issue by jeremiahk** [editorscut/ec010functionalkickstart#3]
Functional Programming Kickstart: Release 0.2
Chapter: 2
Section: 1 - Pure Functions - Playground Support and Live View

Description:
 The  text: 

> Add result to the playground to hold a copy of the Deck we're going to display. Initially set it to freshDeck.
 
is incorrectly formatted as sample code. I am using Books version 2.2. 

<img width="554" alt="Screen Shot 2020-04-19 at 5 20 42 PM" src="https://user-images.githubusercontent.com/8797209/79701372-22c58f80-8262-11ea-882c-3144172a9a90.png">

**Comment by editorscut** [comment]
Thank you - I'm sorry for that. This is fixed for Friday
