### ISSUE TITLE
extra word (possible editing artifact)

### ISSUE THREAD

**Issue by elkssing** [editorscut/ec010functionalkickstart#30]
Functional Programming Kickstart: Release 0.8
Chapter: _1_
Section: _2_

Description: The first sentence of the last full paragraph on page 31 contains an extra word, **to**.

“We also need to be able to determine whether or not two Card instances **to** are equal.”

Excerpt From: Daniel H Steinberg. “A Functional Programming Kickstart.” Apple Books.

**Comment by editorscut** [comment]
I apologize for taking so long to fix this. Fixed for the next release. Thank you
