### ISSUE TITLE
Missing public keyword?

### ISSUE THREAD

**Issue by thuroe** [editorscut/ec010functionalkickstart#31]
Functional Programming Kickstart: Release 0.8
Chapter: _6_
Section: _03ShinyTrunk_
Paragraph FlatMap for ShinyTrunk

Description:
In code extension for the ShinyTrunk it says _func flatMap....._
Ii should read _public func flatMap_ I think.
The example is in 03ShinyTrunk, but the actual extension is being programmed in functor/ShinyTrunk.swift
(error met in xcode 12)

**Comment by dimsumthinking** [comment]
Fixed thank you
