### ISSUE TITLE
Wrong page reference

### ISSUE THREAD

**Issue by thuroe** [editorscut/ec010functionalkickstart#32]
Functional Programming Kickstart: Release 0.8
Chapter: _6_
Section: _10_
Paragraphe State

Description:
When showing code to be entered you show the page in the playground in a smaller font. 
Here the page reference shows _06/FlatMap.playground/08State_, but it should show _06/FlatMap.playground/10State_

**Comment by dimsumthinking** [comment]
Thank you fixed
