### ISSUE TITLE
Editing Artifact

### ISSUE THREAD

**Issue by nickkohrn** [editorscut/ec010functionalkickstart#33]
Functional Programming Kickstart: Release 0.6
Chapter: 1
Section: 5 (Choosing our cards subheading)

Description: The following excerpt seems to be missing the letter _r_ in the word _you_, which is annotated in bold.

“But Daniel," **you** object, "myCard is also a let. You can't change it.”

The suggested fix follows, simply changing _you_ to _your_.

“But Daniel," **your** object, "myCard is also a let. You can't change it.”

**Comment by editorscut** [comment]
I mean this as object (like I object to this) and not the noun object (like that object on the table). I've simplified this to "you say" - thank you.
