### ISSUE TITLE
Equatable example looks like it's returning the wrong result

### ISSUE THREAD

**Issue by samdeane** [editorscut/ec010functionalkickstart#5]
Functional Programming Kickstart: Release 0.1
Chapter: 1
Section: 6

Description:

In your example of covered equitability, the second result ought to be `true`?

![image](https://user-images.githubusercontent.com/206306/80752152-f2fc6e80-8b22-11ea-91e1-a8fa7055315f.png)

**Comment by editorscut** [comment]
Sorry about that - I've corrected that for the update that will post on Friday.

Thank you for taking the time to send this in.

Daniel

**Comment by samdeane** [comment]
No worries. I was sitting there thinking "am I missing something really subtle here?" 😆
