### ISSUE TITLE
Minor errata

### ISSUE THREAD

**Issue by samdeane** [editorscut/ec010functionalkickstart#6]
Functional Programming Kickstart: Release 0.3

I found a few more minor typos, or things that I think might be typos.

**Comment by samdeane** [comment]
Chapter: 2, Section 3

In the sentence “If you can't change which label is being displayed, not what it displays, we've got a very boring app.” did you actually mean **nor** rather than **not**?

**Comment by samdeane** [comment]
Chapter 2, Section 7

In the paragraph “This is looking nicer. Our class is bundling up and converting it into the form our view needs. Let's look at the buttons.” are there some words missing between "up" & "and"? Eg "is bundling up our model"?

**Comment by samdeane** [comment]
Chapter 3, Section 8

In the paragraph “The operator will go between the two things that it is operating on so this will be an infix operator as opposed to a prefix operator that operates on one item and comes before it or a postfix operator that operates on two items and comes after it.” the postfix description should surely say "operates on one item"?

**Comment by samdeane** [comment]
Apologies if these are already fixed in 0.4!

**Comment by editorscut** [comment]
Thank you for these. All are correct and helpful. I've fixed them for the May 8 release.
