### ISSUE TITLE
suggestion - struct vs method

### ISSUE THREAD

**Issue by samdeane** [editorscut/ec010functionalkickstart#7]
Functional Programming Kickstart: Release 0.3
Chapter: 3
Section: 7

Description:

In your discussion of whether it makes sense to represent something as a struct or a function, you imply that the choice can be a bit gut-feeling (like with properties vs methods).

It occurred to me that one quite concrete criteria is whether it's truly a black box, or whether you would ever want to retrieve the parameters you passed in when you created it.

For example, if you're given a line equation, do you ever want to be able to retrieve the values of "m" and "b" independently - in order to display them in a label, perhaps? 

Both the function and the struct form of line capture m and b, but only the struct form gives you the possibility of retrieving them.

Not an earth-shattering insight, I realise 😁

**Comment by editorscut** [comment]
Thank you - I've added a reference to this idea and a pre-sell of the State monad (without using the word Monad of course)
