### ISSUE TITLE
error in sorting by suit and rank

### ISSUE THREAD

**Issue by samdeane** [editorscut/ec010functionalkickstart#8]
Functional Programming Kickstart: Release 0.4
Chapter: 4
Section: 2

Description:

I don't think this does what you meant it to do :)

“Or we could use the point-free approach and chain two calls to sorted() like this.
03/Arrays.playground/02Sorted
result
    = yourHand
        .sorted(by: comparingRanks)
        .sorted(by: comparingSuits)
”

Won't that just end up with the hand sorted by suits?

**Comment by editorscut** [comment]
yes and no.

I thought I explained in the text (but if it's not sufficient I can add more) that 

yourHand.sorted(by: comparingSuits) just sorts by suits and the cards may appear within each suit not in increasing order. If I want them to be sorted by suits but within each suit be in increasing order, I need to first sort by rank. 

If You think I should say more in the text please reopen and I will

**Comment by samdeane** [comment]
What I meant was that in the example above:

```
result = yourHand.sorted{
    if $0.suit == $1.suit {
        return $0.rank < $1.rank
    }
    return $0.suit < $1.suit
}
```

You have combined the logic of both sort criteria. You're saying "if the suits are equal, sort by rank".

You then say "or we could use the point-free approach"... implying that the example you give does the same thing.

It doesn't though. Or at least, it might, but it might not - it's purely dependent on the sort implementation.

What it does is sort the entire hand by rank, then sort the result (which is the entire hand) by suit. You end up with the hand _only guaranteed to be sorted by suit_. Within that sort the other elements might preserve their previous ordering, but (afaik) it's not in the contract of `sorted` that they do. (maybe it is, and I just didn't realise?)

Strictly speaking, to do what I think you meant, I think you'd need to define a new `comparingRankAndSuits` function with a body along the lines of `$0.suit == $1.suit ? comparingRank($0, $1) : comparingSuits($0, $1)`.

**Comment by samdeane** [comment]
(I don't seem to have permission to re-open, but hopefully you'll see these comments)

**Comment by samdeane** [comment]
I may have this backwards and not know that `sorted()` is guaranteed to preserve the previous ordering for elements that are equal, but if so, I'm probably not the only one!

**Comment by samdeane** [comment]
Hurrah for good commenting... Found this in `Sequence`:

```
   /// The sorting algorithm is not guaranteed to be stable. A stable sort
    /// preserves the relative order of elements that compare equal.
 ```

**Comment by editorscut** [comment]
Thank you I have
